# Generated by Django 5.0.4 on 2024-05-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_newuser_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='group',
            new_name='groupss',
        ),
    ]
