# Generated by Django 5.0.4 on 2024-05-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_events_departments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='group',
        ),
        migrations.AddField(
            model_name='departments',
            name='choir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='departments',
            name='instruments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='departments',
            name='usher',
            field=models.BooleanField(default=False),
        ),
    ]
