# Generated by Django 5.0.4 on 2024-05-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_departments_group_departments_choir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='department',
        ),
        migrations.AlterField(
            model_name='departments',
            name='instruments',
            field=models.BooleanField(default=False),
        ),
    ]
