# Generated by Django 5.0.4 on 2024-05-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_remove_departments_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='choir',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='instruments',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='usher',
        ),
        migrations.AddField(
            model_name='departments',
            name='department',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departments',
            name='group',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
