# Generated by Django 5.0.4 on 2024-05-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_remove_departments_choir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='department',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='events',
            name='event',
            field=models.CharField(max_length=400),
        ),
    ]
